version: '3'
services:
    api:
        build: .
        command: bash -c "go get github.com/pilu/fresh && fresh"
        volumes:
            - .:/go/src/sunr
        ports:
            - 8082:8082
        env_file:
            - ./env.list
